In [8]:
import numpy as np
import pandas as pd

In [9]:
df = pd.read_csv(r"C:\Users\LEON SUAREZ\Desktop\VSC\Visualizacion datos\Proyectos de estudio\diamonds.csv", sep = ',')

In [10]:
print(df.shape)
df.head(4)

(53940, 10)

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63

In [11]:
df.carat.sum()

np.float64(43040.87)

In [12]:
df.describe()

,carat,depth,table,price,x,y,z
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,0.797940,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,0.474011,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,0.200000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,0.400000,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000
50%,0.700000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,1.040000,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000
max,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000

In [13]:
df.price.describe()

count    53940.000000
mean      3932.799722
std       3989.439738
min        326.000000
25%        950.000000
50%       2401.000000
75%       5324.250000
max      18823.000000
Name: price, dtype: float64

In [14]:
df.value_counts

<bound method DataFrame.value_counts of        carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]>

In [21]:
df_premium = df[(df.carat > 2)&(df.cut == 'Premium')]
df_premium

       carat      cut color clarity  depth  table  price     x     y     z
12246   2.06  Premium     J      I1   61.2   58.0   5203  8.10  8.07  4.95
15319   2.08  Premium     H      I1   61.7   57.0   6150  8.23  8.18  5.06
15905   2.15  Premium     H      I1   62.9   57.0   6357  8.25  8.20  5.18
15941   2.03  Premium     G      I1   61.1   58.0   6377  8.11  8.06  4.94
16341   2.21  Premium     H      I1   62.2   58.0   6535  8.31  8.27  5.16
...      ...      ...   ...     ...    ...    ...    ...   ...   ...   ...
27731   2.55  Premium     I     VS1   61.8   62.0  18766  8.70  8.65  5.36
27737   2.05  Premium     F     SI2   60.2   59.0  18784  8.28  8.33  5.00
27742   2.04  Premium     H     SI1   58.1   60.0  18795  8.37  8.28  4.84
27744   2.29  Premium     I     SI1   61.8   59.0  18797  8.52  8.45  5.24
27749   2.29  Premium     I     VS2   60.8   60.0  18823  8.50  8.47  5.16

[743 rows x 10 columns]

In [26]:
df_premium.groupby('price').sum()

       carat      cut color clarity  depth  table     x     y     z
price
5203    2.06  Premium     J      I1   61.2   58.0  8.10  8.07  4.95
6150    2.08  Premium     H      I1   61.7   57.0  8.23  8.18  5.06
6357    2.15  Premium     H      I1   62.9   57.0  8.25  8.20  5.18
6377    2.03  Premium     G      I1   61.1   58.0  8.11  8.06  4.94
6535    2.21  Premium     H      I1   62.2   58.0  8.31  8.27  5.16
...      ...      ...   ...     ...    ...    ...   ...   ...   ...
18766   2.55  Premium     I     VS1   61.8   62.0  8.70  8.65  5.36
18784   2.05  Premium     F     SI2   60.2   59.0  8.28  8.33  5.00
18795   2.04  Premium     H     SI1   58.1   60.0  8.37  8.28  4.84
18797   2.29  Premium     I     SI1   61.8   59.0  8.52  8.45  5.24
18823   2.29  Premium     I     VS2   60.8   60.0  8.50  8.47  5.16

[651 rows x 9 columns]

In [28]:
df.agrupado = df.groupby('price')
df.agrupado

In [29]:
df.agrupado.groups

{326: [0, 1], 327: [2], 334: [3], 335: [4], 336: [5, 6], 337: [7, 8], 338: [9], 339: [10], 340: [11], 342: [12], 344: [13], 345: [14, 15], 348: [16], 351: [17, 18, 19, 20], 352: [21], 353: [22, 23, 24], 354: [25], 355: [26], 357: [27, 28, 29, 28260, 28261, 28262, 28263, 28264], 358: [28265], 360: [28266, 28267], 361: [28268, 28269, 28270, 28271], 362: [28272, 28273, 28274, 28275], 363: [28276, 28277, 28278, 28279, 28280], 364: [28281, 28282, 28283], 365: [28284], 366: [28285], 367: [28286, 28287, 28288, 28289, 31590, 31591, 31592, 31593, 31594, 31595, 31596, 31597, 31598, 31599, 31600, 31601, 31602], 368: [31603, 31604, 31605, 31606, 31607, 31608], 369: [31609, 31610, 31611], 370: [31612], 371: [31613, 31614, 31615], 372: [31616], 373: [31617, 31618, 31619, 34920, 34921, 34922, 34923, 34924, 34925, 34926, 34927], 374: [34928, 34929, 34930, 34931, 34932], 375: [34933, 34934], 376: [34935, 34936], 377: [34937, 34938, 34939], 378: [34940, 34941, 34942, 34943, 34944, 34945, 34946, 34947], 379: [34948, 34949, 38250], 380: [38251, 38252, 38253, 38254], 381: [38255], 382: [38256, 38257, 38258, 38259, 38260, 38261, 38262], 383: [38263, 38264, 38265], 384: [38266, 38267, 38268, 38269, 38270, 38271], 385: [38272], 386: [38273, 38274, 38275, 38276, 38277, 38278, 38279], 388: [41580, 41581, 41582, 41583, 41584], 389: [41585, 41586, 41587, 41588, 41589], 390: [41590], 391: [41591, 41592, 41593, 41594, 41595, 41596, 41597, 41598, 41599], 393: [41600, 41601, 41602, 41603, 41604, 41605, 41606, 41607, 41608, 41609, 43980, 43981, 43982], 394: [43983, 43984, 43985, 43986, 43987, 43988, 43989, 43990, 43991, 43992, 43993, 43994, 43995, 43996, 43997, 43998, 43999, 44000, 44001, 44002, 44003, 44004, 44005, 44006, 44007, 44008, 44009, 47280, 47281, 47282, 47283, 47284, 47285, 47286, 47287, 47288, 47289, 47290, 47291, 47292, 47293, 47294, 47295, 47296, 47297, 47298, 47299, 47300], 395: [47301, 47302, 47303], 396: [47304, 47305], 397: [47306, 47307, 47308, 47309, 50610, 50611], 399: [50612, 50613, 50614, 50615, 50616], 400: [50617, 50618, 50619, 50620], 401: [50621, 50622, 50623, 50624, 50625, 50626, 50627], 402: [30, 31, 32, 33, 34, 35, 36, 37, 50628, 50629, 50630, 50631, 50632, 50633, 50634, 50635, 50636, 50637, 50638, 50639], 403: [38, 39, 40, 41, 42, 43, 44, 45, 46, 47], 404: [48, 49, 50, 51, 52, 53, 54], 405: [55, 56, 57, 58, 59, 3360, 3361], 406: [3362], 407: [3363, 3364, 3365, 3366, 3367, 3368, 3369, 3370, 3371, 3372, 3373, 3374], 408: [3375, 3376, 3377, 3378, 3379, 3380, 3381, 3382, 3383, 3384, 3385, 3386, 3387, 3388, 3389, 6690, 6691, 6692, 6693, 6694, 6695, 6696, 6697, 6698], 409: [6699, 6700, 6701], 410: [6702, 6703, 6704], 411: [6705, 6706, 6707], 412: [6708, 6709, 6710], 413: [6711, 6712, 6713, 6714, 6715, 6716, 6717, 6718, 6719, 10020, 10021], 414: [10022, 10023, 10024, 10025, 10026], 415: [10027, 10028], 416: [10029, 10030, 10031], 417: [10032, 10033, 10034, 10035, 10036, 10037, 10038, 10039, 10040], 418: [10041, 10042, 10043, 10044, 10045, 10046, 10047, 10048, 10049], 419: [13350, 13351, 13352, 13353, 13354, 13355, 13356, 13357, 13358, 13359, 13360, 13361, 13362, 13363, 13364, 13365, 13366, 13367, 13368, 13369, 13370, 13371, 13372, 13373, 13374, 13375], 420: [13376, 13377, 13378, 13379, 16680, 16681], 421: [16682, 16683, 16684, 16685, 16686, 16687, 16688, 16689, 16690, 16691, 16692, 16693, 16694, 16695, 16696, 16697, 16698, 16699, 16700, 16701, 16702, 16703, 16704, 16705, 16706, 16707, 16708, 16709, 20010, 20011, 20012, 20013, 20014, 20015, 20016, 20017, 20018, 20019, 20020, 20021, 20022, 20023, 20024, 20025, 20026, 20027, 20028, 20029, 20030, 20031, 20032, 20033, 20034, 20035, 20036, 20037, 20038, 20039, 23340, 23341], 422: [23342, 23343, 23344, 23345, 23346, 23347, 23348, 23349, 23350, 23351, 23352, 23353, 23354, 23355, 23356, 23357, 23358, 23359], 423: [23360, 23361, 23362, 23363], 424: [23364, 23365, 23366], 425: [23367, 23368, 23369, 26670, 26671], 426: [26672, 26673, 26674, 26675, 26676, 26677], 427: [26678, 26679, 26680, 26681, 26682, 26683, 26684, 26685, 26686], 428: [26687, 26688], 429: [26689, 26690, 26691, 26692, 26693, 26694, 26695, 26696, 26697, 26698, 26699, 27930], 430: [27931, 27932, 27933, 27934, 27935, 27936, 27937, 27938], 431: [27939, 27940, 27941, 27942, 27943, 27944, 27945, 27946, 27947], 432: [27948, 27949, 27950, 27951, 27952, 27953, 27954, 27955, 27956, 27957, 27958, 27959, 28290, 28291, 28292, 28293, 28294, 28295, 28296, 28297, 28298, 28299, 28300, 28301, 28302, 28303, 28304, 28305, 28306, 28307, 28308, 28309, 28310, 28311, 28312, 28313, 28314, 28315, 28316, 28317, 28318, 28319, 28620, 28621], 433: [28622, 28623, 28624, 28625], 434: [28626, 28627, 28628, 28629, 28630, 28631, 28632, 28633, 28634, 28635, 28636, 28637, 28638, 28639, 28640, 28641, 28642, 28643, 28644, 28645], 435: [28646, 28647, 28648, 28649, 28950, 28951, 28952, 28953, 28954, 28955, 28956, 28957, 28958, 28959, 28960, 28961, 28962, 28963, 28964, 28965, 28966, 28967, 28968, 28969, 28970, 28971, 28972, 28973, 28974, 28975, 28976, 28977], 436: [28978, 28979, 29280, 29281, 29282, 29283, 29284, 29285, 29286, 29287, 29288, 29289, 29290, 29291, 29292, 29293, 29294, 29295, 29296], 438: [29297, 29298, 29299, 29300, 29301, 29302, 29303, 29304, 29305, 29306, 29307, 29308, 29309, 29610], 439: [29611, 29612, 29613, 29614, 29615, 29616, 29617, 29618, 29619, 29620, 29621], 440: [29622, 29623, 29624], 441: [29625, 29626, 29627, 29628], 442: [29629, 29630, 29631, 29632, 29633, 29634, 29635, 29636, 29637, 29638], 443: [29639, 29940], ...}

In [30]:
df.agrupado.max()

       carat        cut color clarity  depth  table     x     y     z
price
326     0.23    Premium     E     SI2   61.5   61.0  3.95  3.98  2.43
327     0.23       Good     E     VS1   56.9   65.0  4.05  4.07  2.31
334     0.29    Premium     I     VS2   62.4   58.0  4.20  4.23  2.63
335     0.31       Good     J     SI2   63.3   58.0  4.34  4.35  2.75
336     0.24  Very Good     J    VVS2   62.8   57.0  3.95  3.98  2.48
...      ...        ...   ...     ...    ...    ...   ...   ...   ...
18803   2.00  Very Good     H     SI1   62.8   57.0  7.95  8.00  5.01
18804   2.07      Ideal     G     SI2   62.5   55.0  8.20  8.13  5.11
18806   1.51      Ideal     G      IF   61.7   55.0  7.37  7.41  4.56
18818   2.00  Very Good     G     SI1   63.5   56.0  7.90  7.97  5.04
18823   2.29    Premium     I     VS2   60.8   60.0  8.50  8.47  5.16

[11602 rows x 9 columns]